Repository FRONTENDSCHOOL10/LEEKIM, pull requests merged in 2024-09, with the labels that each got.

#5 Feature/header/jinyong
  public/Icon/Logo.svg
  src/components/AppHeader/AppNav/index.tsx
  src/components/AppHeader/components/AppNav/index.tsx
  src/components/AppHeader/components/AppNav/style.module.scss
  src/components/AppHeader/components/BoxButton/index.tsx
  src/components/AppHeader/components/BoxButton/style.module.scss
  src/components/AppHeader/components/HomeButton/index.tsx
  src/components/AppHeader/components/HomeButton/style.module.scss
  src/components/AppHeader/components/SearchBox/index.tsx
  src/components/AppHeader/components/SearchBox/style.module.scss
  src/components/AppHeader/index.tsx
Labels: 🎲Component

#6 Feature/footer/jinyong
  public/Icon/TextLogo.svg
  src/components/AppFooter/Divider/index.tsx
  src/components/AppFooter/Divider/style.module.scss
  src/components/AppFooter/FooterNavigation/index.tsx
  src/components/AppFooter/FooterNavigation/style.module.scss
  src/components/AppFooter/Profile/index.tsx
  src/components/AppFooter/Profile/style.module.scss
  src/components/AppFooter/index.tsx
  src/components/AppFooter/style.module.scss
Labels: 🎲Component

#8 Modify/router/jinyong
  src/router.tsx
  src/routes/Bookmark/assets/asset.png
  src/routes/Bookmark/components/Component.tsx
  src/routes/Bookmark/index.tsx
  src/routes/Bookmark/style.module.scss
  src/routes/EditProfile/assets/asset.png
  src/routes/EditProfile/components/Component.tsx
  src/routes/EditProfile/index.tsx
  src/routes/EditProfile/style.module.scss
  src/routes/Join/assets/asset.png
  src/routes/Join/components/Component.tsx
  src/routes/Join/index.tsx
  src/routes/Join/style.module.scss
  src/routes/MyPage/assets/asset.png
  src/routes/MyPage/components/Component.tsx
  src/routes/MyPage/index.tsx
  src/routes/MyPage/style.module.scss
  src/routes/RegisterExhibition/assets/asset.png
  src/routes/RegisterExhibition/components/Component.tsx
  src/routes/RegisterExhibition/index.tsx
  src/routes/RegisterExhibition/style.module.scss
  src/routes/SearchResults/assets/asset.png
  src/routes/SearchResults/components/Component.tsx
  src/routes/SearchResults/index.tsx
  src/routes/SearchResults/style.module.scss
Labels: ⚙Other

#16 Feat/exhibition detail/siwon
  .env
  index.html
  package.json
  pnpm-lock.yaml
  public/Icon/marker.svg
  public/icon/Bookmark.svg
  public/icon/back.svg
  public/icon/calendar.svg
  public/icon/home.svg
  public/icon/location.svg
  public/icon/web.svg
  src/api/kakaoMap.tsx
  src/env.d.ts
  src/routes/ExhibitionDetail/components/contactinfo/index.tsx
  src/routes/ExhibitionDetail/components/contactinfo/style.module.scss
  src/routes/ExhibitionDetail/components/description/index.tsx
  src/routes/ExhibitionDetail/components/description/style.module.scss
  src/routes/ExhibitionDetail/components/exhibitionDate/index.tsx
  src/routes/ExhibitionDetail/components/exhibitionDate/style.module.scss
  src/routes/ExhibitionDetail/components/imagesection/index.tsx
  src/routes/ExhibitionDetail/components/imagesection/style.module.scss
  src/routes/ExhibitionDetail/components/locationinfo/index.tsx
  src/routes/ExhibitionDetail/components/locationinfo/style.module.scss
  src/routes/ExhibitionDetail/components/tag/index.tsx
  src/routes/ExhibitionDetail/components/tag/style.module.scss
  src/routes/ExhibitionDetail/components/taglist/index.tsx
  src/routes/ExhibitionDetail/components/taglist/style.module.scss
  src/routes/ExhibitionDetail/components/title/index.tsx
  src/routes/ExhibitionDetail/components/title/style.module.scss
  src/routes/ExhibitionDetail/index.tsx
  src/routes/ExhibitionDetail/style.module.scss
  src/types/ExhibitionData.ts
  src/utils/getImageURL.ts
  tsconfig.json
Labels: 🎲Component, ⭐Feature

#20 Design/deletePageScss/Jinyong
  src/styles/_page.scss
  src/styles/main.scss
Labels: 💔Style

#23 Feat/siteintroductio/siwon
  src/routes/Introduce/assets/C.svg
  src/routes/Introduce/assets/J.svg
  src/routes/Introduce/assets/M.svg
  src/routes/Introduce/assets/Subtract.svg
  src/routes/Introduce/assets/contact2.svg
  src/routes/Introduce/assets/dot.svg
  src/routes/Introduce/assets/github.svg
  src/routes/Introduce/assets/introducemain1.png
  src/routes/Introduce/assets/introducemain2.png
  src/routes/Introduce/assets/introducemain3.png
  src/routes/Introduce/assets/introducemain4.png
  src/routes/Introduce/assets/introducemain5.png
  src/routes/Introduce/assets/jaerim.jpg
  src/routes/Introduce/assets/jinyon.png
  src/routes/Introduce/assets/jisoo.jpg
  src/routes/Introduce/assets/likelion.svg
  src/routes/Introduce/assets/logo.svg
  src/routes/Introduce/assets/mail.svg
  src/routes/Introduce/assets/siwon.jpg
  src/routes/Introduce/assets/tel.svg
  src/routes/Introduce/assets/yeongnam.svg
  src/routes/Introduce/components/description/description/descriptionframe/index.tsx
  src/routes/Introduce/components/description/description/descriptionframe/style.module.scss
  src/routes/Introduce/components/description/index.tsx
  src/routes/Introduce/components/description/style.module.scss
  src/routes/Introduce/components/link/index.tsx
  src/routes/Introduce/components/link/style.module.scss
  src/routes/Introduce/components/link/text/index.tsx
  src/routes/Introduce/components/link/text/style.module.scss
  src/routes/Introduce/components/mainTitle/index.tsx
  src/routes/Introduce/components/mainTitle/style.module.scss
  src/routes/Introduce/components/team/index.tsx
  src/routes/Introduce/components/team/member/index.tsx
  src/routes/Introduce/components/team/member/memberlink/index.tsx
  src/routes/Introduce/components/team/member/memberlink/style.module.scss
  src/routes/Introduce/components/team/member/style.module.scss
  src/routes/Introduce/components/team/style.module.scss
  src/routes/Introduce/index.tsx
  src/routes/Introduce/style.module.scss
Labels: 🎲Component, ⭐Feature

#26 feature/TermsOfUse/jaerim
  src/routes/TermsOfUse/components/Component.tsx
  src/routes/TermsOfUse/index.tsx
  src/routes/TermsOfUse/style.module.scss
Labels: 💔Style, 🖥Markup

#28 Feature/login join page/jinyong
  package.json
  pnpm-lock.yaml
  src/components/AppHeader/components/AppNav/index.tsx
  src/routes/Home/index.tsx
  src/routes/Join/components/Divider/index.tsx
  src/routes/Join/components/Divider/style.module.scss
  src/routes/Join/components/SnsJoinButton/index.tsx
  src/routes/Join/components/SnsJoinButton/style.module.scss
  src/routes/Join/index.tsx
  src/routes/Login/components/Divider/index.tsx
  src/routes/Login/components/Divider/style.module.scss
  src/routes/Login/components/SnsLoginButton/index.tsx
  src/routes/Login/components/SnsLoginButton/style.module.scss
  src/routes/Login/index.tsx
  src/stores/isContentPage.ts
  src/stores/isLogin.ts
  src/types/ExhibitionData.ts
  src/utils/getImageURL.ts
Labels: 🎲Component

#31 featrue: 전시 목록 필터 기능 구현 완료
  src/components/ExhibitionSlider/components/ExhibitionInfo/index.tsx
  src/components/ExhibitionSlider/components/ExhibitionInfo/style.module.scss
  src/components/ExhibitionSlider/index.tsx
  src/routes/ExhibitionList/components/Banner/Banner.tsx
  src/routes/ExhibitionList/components/FilterOptions/FilterOptions.tsx
  src/routes/ExhibitionList/components/FilterTag/FilterTag.tsx
  src/routes/ExhibitionList/components/FilterTag/style.module.scss
  src/routes/ExhibitionList/index.tsx
  src/routes/Join/index.tsx
  src/types/TagData.ts
Labels: ⚡Bug, 🎲Component, ⭐Feature

#34 Design/header and footer/jinyong
  public/Icon/IconClearButton.svg
  public/Icon/IconSearchButton.svg
  public/Icon/Logo.svg
  public/Icon/TextLogo.svg
  src/components/AppFooter/components/Divider/style.module.scss
  src/components/AppFooter/components/FooterNavigation/style.module.scss
  src/components/AppFooter/components/Profile/index.tsx
  src/components/AppFooter/components/Profile/style.module.scss
  src/components/AppFooter/index.tsx
  src/components/AppFooter/style.module.scss
  src/components/AppHeader/components/AppNav/index.tsx
  src/components/AppHeader/components/AppNav/style.module.scss
  src/components/AppHeader/components/BoxButton/style.module.scss
  src/components/AppHeader/components/HomeButton/index.tsx
  src/components/AppHeader/components/HomeButton/style.module.scss
  src/components/AppHeader/components/SearchBox/index.tsx
  src/components/AppHeader/components/SearchBox/style.module.scss
  src/components/AppHeader/style.module.scss
Labels: 💔Style, ⭐Feature

#36 Feature/search result/jisoo
  src/routes/ManageExhibition/index.tsx
  src/routes/SearchResults/components/FilterOptions/FilterOptions.tsx
  src/routes/SearchResults/components/FilterOptions/style.module.scss
  src/routes/SearchResults/components/LoadMoreButton/LoadMoreButton.tsx
  src/routes/SearchResults/components/LoadMoreButton/style.module.scss
  src/routes/SearchResults/components/SearchBanner/SearchBanner.tsx
  src/routes/SearchResults/components/SearchBanner/style.module.scss
  src/routes/SearchResults/index.tsx
  src/routes/SearchResults/style.module.scss
  src/stores/searchTerm.ts
Labels: 🎲Component

#39 feature/EditProfile/jaerim
  src/routes/EditProfile/index.tsx
  src/routes/EditProfile/style.module.scss
Labels: 🎲Component

#40 Feature/mainPage/Jinyong
  src/components/ExhibitionSlider/components/ExhibitionInfo/index.tsx
  src/components/ExhibitionSlider/components/ExhibitionInfo/style.module.scss
  src/components/ExhibitionSlider/index.tsx
  src/components/ExhibitionSlider/style.module.scss
  src/components/ExhibitionSlider/style.scss
  src/routes/ExhibitionList/index.tsx
  src/routes/Home/assets/BigSloganImg.png
  src/routes/Home/assets/posterBoxImg.png
  src/routes/Home/components/IngExhibition/index.tsx
  src/routes/Home/components/IngExhibition/style.module.scss
  src/routes/Home/components/MainPosterCard/index.tsx
  src/routes/Home/components/MainPosterCard/style.module.scss
  src/routes/Home/components/MainSlider/index.tsx
  src/routes/Home/components/MainSlider/style.module.scss
  src/routes/Home/components/RecentlyViewedExhibition/index.tsx
  src/routes/Home/components/RecentlyViewedExhibition/style.module.scss
  src/routes/Home/components/RecommendBanner/index.tsx
  src/routes/Home/components/RecommendBanner/style.module.scss
  src/routes/Home/components/Slogan/index.tsx
  src/routes/Home/components/Slogan/style.module.scss
  src/routes/Home/components/SoonExhibition/index.tsx
  src/routes/Home/components/SoonExhibition/style.module.scss
  src/routes/Home/index.tsx
  src/routes/Home/style.module.scss
Labels: 🎲Component, 💔Style, ⭐Feature

#41 Feature/all page/jinyong
  src/components/AppHeader/index.tsx
  src/components/RootLayout/index.tsx
  src/routes/ExhibitionDetail/index.tsx
  src/routes/ExhibitionDetail/style.module.scss
  src/routes/ExhibitionList/components/FilterTag/FilterTag.tsx
  src/routes/Home/components/RecentlyViewedExhibition/index.tsx
  src/routes/Home/components/RecentlyViewedExhibition/style.module.scss
  src/routes/Home/components/Slogan/index.tsx
  src/routes/Introduce/components/team/style.module.scss
  src/routes/Join/index.tsx
  src/routes/Login/index.tsx
  src/routes/ManageExhibition/index.tsx
Labels: ⭐Feature, ⚙Other

#47 Feature/search result/jisoo
  public/Icon/IconCheckbox.svg
  public/Icon/IconSortArrow.svg
  src/routes/Introduce/assets/jisoo.jpg
  src/routes/SearchResults/components/FilterOptions/style.module.scss
  src/routes/SearchResults/components/LoadMoreButton/style.module.scss
  src/routes/SearchResults/components/SearchBanner/SearchBanner.tsx
  src/routes/SearchResults/components/SearchBanner/style.module.scss
  src/routes/SearchResults/index.tsx
  src/routes/SearchResults/style.module.scss
Labels: 💔Style, ⭐Feature

#48 Design/manage exhibition/jisoo
  src/routes/ManageExhibition/components/BackButton/style.module.scss
  src/routes/ManageExhibition/style.module.scss
Labels: 💔Style

#50 Feature/my page/jinyong
  src/routes/MyPage/index.tsx
Labels: 🎲Component, ⭐Feature

#54 Modify/editProfile/Jinyong
  src/routes/EditProfile/index.tsx
  src/types/UserData.ts
Labels: 🎲Component, 🚫TypeScript, ⭐Feature

#55 Design/header/Jinyong
  src/components/AppHeader/components/AppNav/style.module.scss
  src/components/AppHeader/components/HomeButton/style.module.scss
Labels: 💔Style

#57 Feature/search/Jinyong
  src/components/AppHeader/components/SearchBox/index.tsx
  src/components/AppHeader/components/SearchBox/style.module.scss
Labels: ⭐Feature

#58 Feature/helmet/jisoo
  package.json
  pnpm-lock.yaml
  src/components/CommonHelmet/index.tsx
  src/main.tsx
  src/routes/Bookmark/index.tsx
  src/routes/EditProfile/index.tsx
  src/routes/ExhibitionDetail/index.tsx
  src/routes/ExhibitionList/index.tsx
  src/routes/Home/index.tsx
  src/routes/Introduce/index.tsx
  src/routes/Join/index.tsx
  src/routes/Login/index.tsx
  src/routes/MyPage/index.tsx
  src/routes/RegisterExhibition/index.tsx
  src/routes/SearchResults/index.tsx
Labels: ⚙Other

#61 Modify/my page/jinyong
  public/Icon/IconBookmark.svg
  public/Icon/IconLinkButton.svg
  public/icon/Bookmark.svg
  src/routes/MyPage/index.tsx
  src/routes/MyPage/style.module.scss
Labels: 💔Style

#52 Feature/exhibition list/jaerim
  public/Icon/IconClose.svg
  public/Icon/IconFilter.svg
  src/routes/ExhibitionList/components/Banner/Banner.tsx
  src/routes/ExhibitionList/components/Banner/style.module.scss
  src/routes/ExhibitionList/components/FilterTag/FilterTag.tsx
  src/routes/ExhibitionList/components/FilterTag/style.module.scss
  src/routes/ExhibitionList/index.tsx
  src/routes/ExhibitionList/style.module.scss
Labels: 💔Style

#63 Feat/detail/siwon
  src/routes/ExhibitionDetail/components/moreExhibition/index.tsx
  src/routes/ExhibitionDetail/components/moreExhibition/style.module.scss
  src/routes/ExhibitionDetail/index.tsx
  src/routes/ExhibitionDetail/style.module.scss
Labels: 🎲Component

#67 Feature/my page/jaerim
  public/Icon/Check_none.svg
  src/routes/Join/index.tsx
  src/routes/Join/style.module.scss
  src/routes/Login/index.tsx
  src/routes/Login/style.module.scss
Labels: 💔Style

#69 feature/ExhibitionDetail/jaerim
  public/icon/back.svg
  public/icon/calendar.svg
  public/icon/home.svg
  public/icon/location.svg
  src/routes/ExhibitionDetail/components/description/style.module.scss
  src/routes/ExhibitionDetail/components/locationinfo/style.module.scss
  src/routes/ExhibitionDetail/components/tag/style.module.scss
  src/routes/ExhibitionDetail/components/title/style.module.scss
  src/routes/ExhibitionDetail/style.module.scss
Labels: 💔Style

#70 Design/exhibition list/jisoo
  src/components/ExhibitionSlider/components/ExhibitionInfo/style.module.scss
  src/routes/EditProfile/style.module.scss
  src/routes/ExhibitionList/components/Banner/Banner.tsx
  src/routes/ExhibitionList/components/Banner/style.module.scss
  src/routes/ExhibitionList/components/Component.tsx
  src/routes/ExhibitionList/components/FilterOptions/style.module.scss
  src/routes/ExhibitionList/components/FilterTag/FilterTag.tsx
  src/routes/ExhibitionList/components/FilterTag/style.module.scss
  src/routes/ExhibitionList/index.tsx
  src/routes/ExhibitionList/style.module.scss
  src/routes/Home/components/Component.tsx
  src/routes/Introduce/components/Component.tsx
  src/routes/Introduce/components/description/description/descriptionframe/style.module.scss
  src/routes/Introduce/components/description/style.module.scss
  src/routes/Introduce/components/link/text/style.module.scss
  src/routes/Introduce/components/mainTitle/style.module.scss
  src/routes/Introduce/style.module.scss
  src/routes/Join/components/Component.tsx
  src/routes/Login/components/Component.tsx
  src/routes/ManageExhibition/components/Component.tsx
  src/routes/ManageExhibition/style.module.scss
  src/routes/RegisterExhibition/style.module.scss
  src/routes/SearchResults/components/Component.tsx
  src/routes/SearchResults/components/FilterOptions/style.module.scss
  src/routes/SearchResults/components/LoadMoreButton/style.module.scss
  src/routes/SearchResults/components/SearchBanner/style.module.scss
  src/routes/TermsOfUse/components/Component.tsx
Labels: 🎲Component, 💔Style

#72 Fix/join/Jinyong
  src/routes/EditProfile/index.tsx
  src/routes/Join/index.tsx
  src/routes/MyPage/index.tsx
  src/routes/MyPage/style.module.scss
  src/types/UserData.ts
Labels: 🔗DataBase

#73 Feature/bookmarkPage/Jinyong
  src/components/AppFooter/index.tsx
  src/routes/Bookmark/components/BookmarkBanner/BookmarkBanner.tsx
  src/routes/Bookmark/components/BookmarkBanner/style.module.scss
  src/routes/Bookmark/components/FilterOptions/FilterOptions.tsx
  src/routes/Bookmark/components/FilterOptions/style.module.scss
  src/routes/Bookmark/components/LoadMoreButton/LoadMoreButton.tsx
  src/routes/Bookmark/components/LoadMoreButton/style.module.scss
  src/routes/Bookmark/index.tsx
  src/routes/Bookmark/style.module.scss
  src/routes/ExhibitionDetail/components/description/index.tsx
  src/routes/MyPage/index.tsx
Labels: ⭐Feature

#77 feature/edit/jaerim
  src/routes/Introduce/components/description/style.module.scss
  src/routes/Introduce/components/team/index.tsx
  src/routes/Introduce/components/team/member/memberlink/index.tsx
  src/routes/Introduce/components/team/member/style.module.scss
Labels: 💔Style, ⭐Feature

#79 Feature/all/jisoo
  src/components/CommonHelmet/index.tsx
  src/routes/Bookmark/index.tsx
  src/routes/ExhibitionList/index.tsx
  src/routes/ManageExhibition/index.tsx
  src/routes/SearchResults/index.tsx
Labels: ⚙Other

#81 Feature/loadingSpinner/Jinyong
  src/components/AppSpinner/index.tsx
  src/components/AppSpinner/style.module.scss
  src/routes/ExhibitionDetail/index.tsx
  src/routes/Home/components/IngExhibition/index.tsx
  src/routes/Home/components/MainPosterCard/index.tsx
  src/routes/Home/components/RecentlyViewedExhibition/index.tsx
  src/routes/Home/components/SoonExhibition/index.tsx
  src/routes/ManageExhibition/index.tsx
Labels: 💔Style, ⭐Feature

#82 Feature/term of use/jisoo
  src/routes/TermsOfUse/components/BackButton/BackButton.tsx
  src/routes/TermsOfUse/components/BackButton/style.module.scss
  src/routes/TermsOfUse/index.tsx
  src/routes/TermsOfUse/style.module.scss
Labels: 🎲Component, 💔Style

#85 docs: README.md 수정 1차
  README.md
Labels: 📃Documentation
